apiVersion: v1
kind: Pod
metadata:
  name: poc-app2
spec:
  containers:
  - name: poc-app2
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \"$(date -u) - PoC APP 2 \" >> /data/out2.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: poc-app-pvc